"""empty message

Revision ID: 415cf4ed6d1e
Revises: 90221946f725
Create Date: 2018-08-02 14:34:05.883159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415cf4ed6d1e'
down_revision = '90221946f725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definitions', sa.Column('body', sa.String(length=140), nullable=True))
    op.add_column('definitions', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('definitions', sa.Column('tweet_date', sa.DateTime(), nullable=True))
    op.add_column('definitions', sa.Column('tweet_id', sa.String(), nullable=True))
    op.add_column('definitions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('definitions', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_definitions_timestamp'), 'definitions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_definitions_tweet_id'), 'definitions', ['tweet_id'], unique=False)
    op.drop_index('ix_definitions_latin_word', table_name='definitions')
    op.create_index(op.f('ix_definitions_latin_word'), 'definitions', ['latin_word'], unique=False)
    op.create_foreign_key(None, 'definitions', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'definitions', type_='foreignkey')
    op.drop_index(op.f('ix_definitions_latin_word'), table_name='definitions')
    op.create_index('ix_definitions_latin_word', 'definitions', ['latin_word'], unique=1)
    op.drop_index(op.f('ix_definitions_tweet_id'), table_name='definitions')
    op.drop_index(op.f('ix_definitions_timestamp'), table_name='definitions')
    op.drop_column('definitions', 'username')
    op.drop_column('definitions', 'user_id')
    op.drop_column('definitions', 'tweet_id')
    op.drop_column('definitions', 'tweet_date')
    op.drop_column('definitions', 'timestamp')
    op.drop_column('definitions', 'body')
    # ### end Alembic commands ###
