"""update

Revision ID: 4e90c19aaa5f
Revises: c7c310845d77
Create Date: 2018-07-18 04:28:14.693099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e90c19aaa5f'
down_revision = 'c7c310845d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('tweet_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_entry_tweet_id'), 'entry', ['tweet_id'], unique=False)
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.drop_index(op.f('ix_entry_tweet_id'), table_name='entry')
    op.drop_column('entry', 'tweet_id')
    # ### end Alembic commands ###
