"""add tweet id

Revision ID: a45d42b31581
Revises: c7c310845d77
Create Date: 2018-07-17 14:58:31.508465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45d42b31581'
down_revision = 'c7c310845d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('tweet_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_entry_tweet_id'), 'entry', ['tweet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_tweet_id'), table_name='entry')
    op.drop_column('entry', 'tweet_id')
    # ### end Alembic commands ###
