"""entries table

Revision ID: c7c310845d77
Revises: d58f2f261e9e
Create Date: 2018-07-17 12:20:29.164514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c310845d77'
down_revision = 'd58f2f261e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('english_word', sa.String(), nullable=True),
    sa.Column('latin_top_choice', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('tweet_date', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_english_word'), 'entry', ['english_word'], unique=True)
    op.create_index(op.f('ix_entry_latin_top_choice'), 'entry', ['latin_top_choice'], unique=False)
    op.create_index(op.f('ix_entry_timestamp'), 'entry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_timestamp'), table_name='entry')
    op.drop_index(op.f('ix_entry_latin_top_choice'), table_name='entry')
    op.drop_index(op.f('ix_entry_english_word'), table_name='entry')
    op.drop_table('entry')
    # ### end Alembic commands ###
