"""Votes

Revision ID: ff7d773e0ca8
Revises: 90221946f725
Create Date: 2018-08-07 14:08:27.917013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7d773e0ca8'
down_revision = '90221946f725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definitions', sa.Column('votes', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'definitions', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'definitions', type_='foreignkey')
    op.drop_column('definitions', 'votes')
    # ### end Alembic commands ###
